### ISSUE TITLE
Error installing Part-DB on a Raspberry Pi in a Docker Container

### ISSUE THREAD

**Issue by mrWheel** [Part-DB/Part-DB-symfony#103]
**Describe the bug**
Docker install exits with an error

**To Reproduce**
docker build ../Part-DB

**Expected behavior**
Ending with a "all is good" message.

**Server Side**
- Part-DB Version: 1.0.0-alpha
- PHP Version: [don't know]
- Database Server [SQLite]

**Desktop (please complete the following information):**
 - OS: [Raspbian]
 - Version [9.4]

**Additional context**
Has anybody had any luck installing Part-DB in a Docker container on a RPi?

I'm stuck with this message:
<pre>
Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 952
                                                                                                       
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                       
  The process "'/usr/local/bin/php' './bin/console' cache:clear" exceeded the timeout of 300 seconds.  
                                                                                                       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

The command '/bin/sh -c composer install -a --no-dev && composer clear-cache' returned a non-zero code: 1
</pre>

**Comment by jbtronics** [comment]
Looks like the Pi ran out of memory during the docker build. What RAM has your Pi and have you activated swap memory?

**Comment by mrWheel** [comment]
@jbtronics 
You where right! Changed the swap size to 1024Mb and now the installation has completed!
Thanks!

Next problem:
I now have these containers:
<pre>
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
&lt;none&gt;              &lt;none&gt;              5a76dae5fd52        23 minutes ago      776MB
composer            latest              0ea678e69019        34 hours ago        139MB
php                 7-apache            be60c7ec4b92        2 days ago          300MB
</pre>
How do I start the part-db suite?
Using `sudo` docker-compose up -d` simply rebuilds from scratch which will not get me to a working installation.

Help is much appreciated!

**Comment by mrWheel** [comment]
I did the following (maybe it is to use for somebody)

  [1]
created maps
<pre>
sudo mkdir /var/www/part-db
sudo mkdir /var/www/part-db/uploads
sudo mkdir /var/www/part-db/public
sudo mkdir /var/www/part-db/public/media
</pre>
 [2]
copy Part-DB-Symphony-master.zip` to `/home/pi`

 [3]
<pre>
cd /home/pi
unzip Part-DB-Symphony.zip
docker build Part-DB-Symphony
</pre>
this will take a while with some warnings and errors but all seem to go well..
<pre>
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
&lt;none&gt;              &lt;none&gt;              38a------082        4 hours ago         776MB
composer            latest              0ea------019        42 hours ago        139MB
php                 7-apache            be6------b92        2 days ago          300MB
</pre>
 [4]
The main image of interest has the tag &lt;none&gt; which is not very handy. The IMAGE ID is different from the ones shown above.
<pre>
docker image tag  38a------082:part-db part-db:latest
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
part-db             latest              38a51a212082        4 hours ago         776MB
composer            latest              0ea678e69019        42 hours ago        139MB
php                 7-apache            be60c7ec4b92        2 days ago          300MB
</pre>
 [5]
In `/var/www/part-db` I created two files:
**startPartDb.sh**
<pre>
#!/bin/bash
#
# install part-db:
#	docker build ./Part-DB-symfony-master
#	docker image tag  <image ID>:part-db part-db:latest
#
# ./startPartDB.sh
# and than:
#	docker exec --user=www-data rPartsDB bin/console doctrine:migrations:migrate
#
#
x=$(docker container ls | grep "rPartsDB" | grep " Up " | wc -l)
if [[ ${x} != "0" ]]; then
	echo "rPartsDB already running ..."
	exit
fi
#
x=$(docker container ls -a | grep rPartsDB | wc -l)
if [[ ${x} != "0" ]]; then
	echo "remove stopped containers"
	##docker container prune
	docker rm rPartsDB
	exit
fi
#
#
echo "docker run -d --name rPartsDB "
echo "     -v /var/www/part-db/uploads:/var/www/html/uploads "
echo "     -v /var/www/part-db/public/media:/var/www/html/public_media "
echo "     -p 8080:80 part-db"
echo " "
#
docker run -d --name rPartsDB \
           -v /var/www/part-db/uploads:/var/www/html/uploads \
           -v /var/www/part-db/public/media:/var/www/html/public_media \
           -p 8080:80 part-db 
#
echo "Done!"
</pre>
and **stopPartDb.sh**
<pre>
#!/bin/bash
#
echo "docker container stop  rPartsDB"
docker container stop  rPartsDB
#
echo "docker rm rPartsDB"
docker rm rPartsDB
#
echo "Done!"
</pre>
You can now start part-db by simply starting the starPartDb.sh script.
What I did after the first start was run the next command. Not sure if this is necessary.
<pre> 
docker exec --user=www-data rPartsDB bin/console doctrine:migrations:migrate
</pre>
I'm quite new to docker and to `part-db` so there are probably better ways to do this, but it works for me!
