### ISSUE TITLE
Error 500 when loading part with empty distributor field

### ISSUE THREAD

**Issue by marklinmax** [Part-DB/Part-DB-symfony#116]
**Describe the bug**
When setting a part with purchasing information, if the distributor field is empty, the operation will succeed, but trying to load the part again after this will throw an error 500.

**To Reproduce**
Create a new part or modify one to set ordering information.
Leave the distributor field empty and save.
Try to load the part again.

**Server Side**
- Part-DB Version: docker hub latest
- Database Server Mariadb latest

**Desktop (please complete the following information):**
 - Browser Firefox

Either the fetch needs to be protected in case of empty fields, or the problematic fields should never be allowed to be empty.

**Comment by jbtronics** [comment]
Similar to issue #131, This should not be possible anymore (at least for new orderinfos) as validation now fails, when the supplier is missing.
For existing wrong orderdetails (which throws this error), you have to delete the orderdetail manually.

If the page for example the page http://localhost:8000/en/part/2/info is not accessible, change the URL to http://localhost:8000/en/part/2/edit and you can delete the faulty orderdetail.
