### ISSUE TITLE
"Order Date" field right below the Order Number field

### ISSUE THREAD

**Issue by microplayer** [Part-DB/Part-DB-symfony#119]
**Describe the solution you'd like**
A separate "order date" field right below the order number would be helpful finding purchase information - saved as PDFs for example - in subdirectories saved on a PC..  

**Describe alternatives you've considered**
None found. Re-using the "Link to offer" field is not an option

**Additional context**

**Comment by jbtronics** [comment]
The ordernumber field is not used for order which were placed, but to set the supplier part number under which the part can be ordered. See related issue #198 

So this is not really possible
