### ISSUE TITLE
%PARTNUMBER% instead of %PARTNR%

### ISSUE THREAD

**Issue by soundstorm** [Part-DB/Part-DB-symfony#130]
When creating a supplier the input placeholder and hint tells one to use `%PARTNR%` for the URL, but the `str_replace` is set to `%PARTNUMBER%`.

**Comment by coeka** [comment]
Same as https://github.com/Part-DB/Part-DB-symfony/issues/84

**Comment by jbtronics** [comment]
Should be fixed now.
