### ISSUE TITLE
Maybe an error in the description Part-DB-symfony/docs/docker/docker-install.md

### ISSUE THREAD

**Issue by christiannolte** [Part-DB/Part-DB-symfony#134]
**Describe the bug**
Following the steps from
https://github.com/Part-DB/Part-DB-symfony/blob/master/docs/docker/docker-install.md#direct-use-of-docker-image 
cause a problem

**To Reproduce**
1. **create a directory media for the volume**
2. **create a directory uploads for the volume**
3. **Start the image jbtronics/part-db1:master** with the two mentioned volumes given to the container
like
docker run  --rm --name part-db1 \
  -p 9999:80 \
  -e APP_ENV=prod \
  -v /root/parts/uploads:/var/www/html/uploads \
  -v /root/parts/media:/var/www/html/public/media \
  jbtronics/part-db1:master
   
4. **Execute Step 4 like mentioned**

docker exec --user=www-data part-db1 bin/console doctrine:migrations:migrate

5. **This will result in an error**

In AbstractSQLiteDriver.php line 83:

  An exception occurred in driver: SQLSTATE[HY000] [14] unable to open databa
  se file

In Exception.php line 18:

  SQLSTATE[HY000] [14] unable to open database file

In PDOConnection.php line 40:

  SQLSTATE[HY000] [14] unable to open database file

**Additional context**
When not using volumes everything is fine. So using volumes is overwriting/overlaying e.g. the database app.db.
Maybe there should be a step to create the database in the volume.

Thanks
   Christian

**Comment by christiannolte** [comment]
Ich habe versucht mit 
docker cp container:/var/www/html/uploads/app.db
in mein Volume zu kopieren und dann das Volume zu übergeben, das hat aber leider nicht geklappt.

**Comment by jbtronics** [comment]
This is indeed an issue with the mapping of the database file. By default, the db lives inside the var/ folder which is not mapped. 
You have to put it inside a mapped folder via the `DATABASE_URL` env. I added some hint about this to the docker-install.md and updated the docker-compose.yaml example to use this.
