### ISSUE TITLE
Mfg Part #, Labels, Footprints

### ISSUE THREAD

**Issue by jagauthier** [Part-DB/Part-DB-symfony#157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This is a support request and feature request.

Feature:
Part Creation:  Under the purchase information there is a the ability to add a distributor. Including the distributor part number here would be useful.  Both digikey and mouser have APIs that could be leveraged for informational purposes (long time thought)

Support:
Went to part. Generated a label.  Label doesn't seem to save to the part.  If I want to reprint I need to regen the label details.

Footprint:
I am pretty confused about the intent of footprint and footprint 3d.

In my part I added a "footprint" like so:
![image](https://user-images.githubusercontent.com/7101432/182668749-8106d259-45f9-4bb1-b54c-b60e794d14e5.png)

In my parts list I see that as an icon:
![image](https://user-images.githubusercontent.com/7101432/182668946-7ceb84bf-3f11-4c0a-9336-af3db9de614e.png)

But the footprint column is empty.  I tried adding a 3D foot print a couple times, but I couldn;t see the purpose of that within the application itself.

Thanks for reading!

**Comment by jbtronics** [comment]
> Part Creation: Under the purchase information there is a the ability to add a distributor. Including the distributor part number here would be useful. Both digikey and mouser have APIs that could be leveraged for informational purposes (long time thought)

I do not really see a difference to the existing order nr. field here...



> Footprint: I am pretty confused about the intent of footprint and footprint 3d.
> 
> In my part I added a "footprint" like so:

Footprints are a thing like a category, that you create globally once (via Edit -> Footprints) and then you can select it under parts. You can attach pictures to a footprint which are shown for all parts which are have this footprint (as long as they do not have their own preview picture).

You most likely has only created an attachment on the part, which is more useful for things like datasheets, or if you want to attach an part which only applies to this part.

The `footprint` and `footprint (3D)` attachment types are for compatibility reasons with the old Part-DB versions, where footprint images were handled differently.
