### ISSUE TITLE
Remove "Root Node"

### ISSUE THREAD

**Issue by iyzpx** [Part-DB/Part-DB-symfony#158]
**Describe the solution you'd like**
To enhance usability, the "root node" should either be folded out by default or not displayed at all as in the old version of part-db. It would be also useful when the default datasources can be changed for everyone.

**Additional context**
part-db 0.6: https://i.pewx.de/yzw/ZoyOWOxI09.png/raw
part-db 1.0: https://i.pewx.de/yzw/CUkUqIhI93.png/raw

I think there is no need for that "Root node"

**Comment by jbtronics** [comment]
You can now configure whether a root node should be shown or not by the ` partdb.sidebar.root_node_enable` parameter in `config/parameters.yaml`. By default, the node is expanded.

So I guess this is fixed now
