### ISSUE TITLE
Searches pull all parts

### ISSUE THREAD

**Issue by jagauthier** [Part-DB/Part-DB-symfony#165]
I just did a new pull (docker, actually) and discovered that any and all searches always return all parts.

![image](https://user-images.githubusercontent.com/7101432/183481723-6379b57c-3eba-4aec-8b66-006081ec2045.png)

**Comment by jbtronics** [comment]
That is not related to this issue, but you should really clear your browser cache. The formatting seems very wrong, which is most likely caused by some style mixup. Clearing browser cache should fix that

**Comment by jbtronics** [comment]
Fixed now.

**Comment by jagauthier** [comment]
Browser only did the weird search bar the one time. And thanks for fixing!
