### ISSUE TITLE
Footprint URL fails when containing a comma

### ISSUE THREAD

**Issue by jagauthier** [Part-DB/Part-DB-symfony#166]
I have a script that pulls photos from digikey.  
Digikey part number 490-13293-1-ND has a photo url of:
https://media.digikey.com/Renders/Murata%20Renders/0402-(1005-Metric)-0,55mm.jpg 

This is stored in the database correctly, but the web interface is choking on the comma.
![image](https://user-images.githubusercontent.com/7101432/183493344-a7675592-4801-40b2-9477-d822f9a0634d.png)

Not a problem until a change is made and then it says that it is an invalid url.

**Comment by jbtronics** [comment]
Should be fixed now

**Comment by jagauthier** [comment]
Thanks man!
