### ISSUE TITLE
Error measurement unit without a unit symbol and activated SI prefix

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#171]
I forgot to maintain the unit symbol for my measurement unit and activated the SI prefix:

![Unbenannt](https://user-images.githubusercontent.com/59479028/187996577-2f634a84-d890-4a71-8b5d-36eb3043ee2b.JPG)

After you do that, you can't open the category, where your part is stored. If you open your part directly you get this message:
![image](https://user-images.githubusercontent.com/59479028/187996869-df720a8a-7af0-4427-916b-167cd77591f9.png)

If you did the same mistake, it is still possible to edit the measurement unit and maintain a unit symbol or deactivate the SI prefix.

I tried it with my local part db and with http://part-db.herokuapp.com/en/ as well.

**Comment by jbtronics** [comment]
The exception is now fixed.
Also, it is now forbidden to enable the SI unit prefix option, without setting a symbol, as it is not very useful and could cause confusion with other units.
