### ISSUE TITLE
manual Installation yarn eror

### ISSUE THREAD

**Issue by hwa59** [Part-DB/Part-DB-symfony#183]
I try to install  the Part-DB manually with you installation Guide. The step "yarn install"  give  the following error "00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by jbtronics** [comment]
This sounds like you have installed the wrong `yarn` command. By default debian based distros installs another software called `yarn`, when using the default repos, which has nothing to do with the node package manager you need.

You have to add the yarn repository first, before running `apt install yarn` (and you will have to remove the currently installed yarn first)

**Comment by hwa59** [comment]
Thank you that was my mistake
