### ISSUE TITLE
Category-Table List // wrong Amount 

### ISSUE THREAD

**Issue by Anthrina** [Part-DB/Part-DB-symfony#190]
**Describe the bug**
In the Categorie-Table list the Amount is wrong when you have more than one stocks.
In der Kategorie-Tabellenansicht ist die Menge von Teilen falsch, wenn man mehr als einen Lagerplatz darin hat.

**To Reproduce**
1. Go to 'Categories XY' / Auf Kategorie XY gehen
2. Make one new part with two stocks (first with 1 Amount / second with 4 Amount) / Ein neues Teil anlegen mit zwei Lagerplätzen (erstes mit Menge 1 / zweites mit Menge 4)
3. Go back to 'Categories XY' / Zurück auf Kategorie XY gehen
4. Activate "Amount" / Menge aktivieren
5. See the wrong Amount of the new part. It shows only one of the stocks. / Du siehst das eine falsche Menge beim neuen Teil angezeigt wird. Es zeigt nur eines der beiden Lagerplätze

**Expected behavior**
It shoult show the complete Amount of all stocks. The right Amount you can see only in the Detail-Site of the Part but not in the Category-Table list.
Es sollte die komplette Menge aller Lagerplätze angezeigt werden. Diese sieht man nur auf der Teile-Detail Seite aber nicht in der Kategorie Tabellenansicht.

**Screenshots**
<img width="1289" alt="Amount-Stocks" src="https://user-images.githubusercontent.com/117853542/200907074-d4c999ec-8811-42d2-9423-392ffaebd506.png">

**Server Side**
- Part-DB Version: Part-DB 1.0.0-alpha

**Desktop (please complete the following information):**
 - Browser: Edge & Firefox

**Comment by jbtronics** [comment]
I looked into it a bit and it seems to be caused by the fact, that the ORM only fetches the first element of this collection (similar stuff maybe happens for attachments and price infos too), when doing the (pretty complex) query for the table.

I am not sure if this is a bug in my code or in doctrine. The whole FetchJoin Querying stuff of doctrine is pretty complex, I will try to investigate it a bit.

**Comment by virtadpt** [comment]
Is there anything specific we can do to help?

**Comment by jbtronics** [comment]
Should be fixed now.
