### ISSUE TITLE
Gap in part listing if description is set

### ISSUE THREAD

**Issue by iyzpx** [Part-DB/Part-DB-symfony#192]
**Describe the bug**
Not really a bug, but it doesn't looks that nice. When set a description for a part, the gap in every listing between each part is higher. 

**To Reproduce**
Set a description for a part and go to a listing

**Expected behavior**
Same gap between every part; smallest possible like when no description is set

**Screenshots**
https://i.pewx.de/yzw/DaDUzOmA79.png

**Server Side**
- Part-DB Version: [ffceb5a](https://github.com/Part-DB/Part-DB-symfony/commit/ffceb5abc573a257efa3508ece8a2cf82149ff22)
- PHP Version: 8.1.12
- Database Server [SQLite]

**Comment by jbtronics** [comment]
Thanks for the hint. The useless margin is now removed.
