### ISSUE TITLE
No multiline in part description allowed

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#195]
Not sure if it's a bug or feature, but in the input field of the part descriptions, no new lines are allowed:
![image](https://user-images.githubusercontent.com/1753222/205441034-f0706bbd-91e8-4394-b551-e9cb79a8b6eb.png)

Just using the latest master: 81abf36867f64d7a029f3311f07f30e31adae77f

**Comment by jbtronics** [comment]
This is the intended behavior. The description field should just be a short description of a part, that should not be so long that explicit breaks are needed. Also additional new lines make proper formatting in the part table difficult.

This behavior is  similar to the legacy Part-DB versions, where also only one line was allowed.

**Comment by tbnobody** [comment]
Thank you for this clarification. What would be the "normal" workflow to insert a multiline description for a item? Is this something what should go into the "Kommentar" section?

**Comment by jbtronics** [comment]
Yeah, longer texts should go into the comment field of a part. There you can use many formatting options, and can write very long texts.
