### ISSUE TITLE
Part name hint and description

### ISSUE THREAD

**Issue by deafloo** [Part-DB/Part-DB-symfony#196]
**Describe the bug**
When setting a part name hint and default description in the advanced section of the categories, it does not show up when creating a new part in that category.

**To Reproduce**
1. Create new Category
2. On 'Advanced' section, set 'Part name hint'
3. Create new Element in that category

**Expected behavior**
The part name hint should be displayed in 'Part name' 

**Server Side**
- Part-DB Version: Part-DB 1.0
- PHP Version: don't know
- Database Server SQLite

**Desktop (please complete the following information):**
 - OS: Raspbian Buster
 - Browser Chromium

**Comment by jbtronics** [comment]
Is now fixed.
