### ISSUE TITLE
Add Supplier part number in Purchase information

### ISSUE THREAD

**Issue by elperepat** [Part-DB/Part-DB-symfony#198]
**Is your feature request related to a problem? Please describe.**
When dealing with suppliers, they often have their own part number, different from manufacturer part number.

**Describe the solution you'd like**
A new field named "Supplier part number" added to the "Purchase information" tab for each supplier  would solve this issue.

**Describe alternatives you've considered**
Adding that information to comment, but wouldn't be as clear as a new field when dealing with multiple suppliers for a part as each have their own part number for the same product.

**Additional context**
See example for a simple fuse and different suppliers in screenshot.

![Digikey example](https://user-images.githubusercontent.com/3879635/207145290-a2e74669-13e5-41be-ab7f-a8f15ae0ef0f.png)
![Mouser example](https://user-images.githubusercontent.com/3879635/207145292-7a5c3dc9-2fac-4792-99e9-5b4d9e4344cb.png)

**Comment by jbtronics** [comment]
I would say, that this is the "order number" field in the priceinformation tab, or is there any reason that you can not use it for this?

<img width="620" alt="image" src="https://user-images.githubusercontent.com/5410681/207154861-ddd87ec6-5b2a-4baa-9155-3adf3b3d436f.png">

**Comment by elperepat** [comment]
I was actually tracking the order number (invoice number of the actual order) in there. But yeah, I guess it could serve that purpose instead.

But I see it now, the value entered here is listed in the column "Partnr." when I show the "Shopping information" tab when not in edit mode. There would be a cleanup to do in this area. When editing, the label is "Order number". Maybe it should be changed to "Supplier part number". Same thing with the supplier: the green button in edit mode is "Add distributor". I think it should be "Add supplier".


By the way, thanks for developing and maintaining partDB. There really isn't anything quite like it and it's much needed.

Pat

**Comment by jbtronics** [comment]
Yeah maybe the labeling in english is a bit misleading, I can change that.

As you can order a part multiple times from the same supplier, and invoice numbers are not really part related, an invoice number would be more interesting for an (not yet existing) order system.

**Comment by jbtronics** [comment]
Fixed now.
