### ISSUE TITLE
How to change the amount of an item?

### ISSUE THREAD

**Issue by Dschadu** [Part-DB/Part-DB-symfony#201]
Hi,

sorry if I'm missing it, but how do I change the amount of an item? Only way I found is:
Click the part -> Edit (the Button behind the Name) -> Stocks -> Change the Number manually. 

There has to be an easier way, like with the old PartDB?
https://www.mikrocontroller.net/wikifiles/4/44/Parts_info.png

What am I missing? Thanks in advance!

**Comment by jbtronics** [comment]
Currently editing the instock via the edit page is the only possibility. 
But i will add the feature that you can easily add or subtract (or move) instock from the part info page. 

This is a bit more difficult than in the older Part-DB versions, as now a part can have stocks at multiple locations.

**Comment by jbtronics** [comment]
In the latest version there is now a modal for easy withdrawal/addition of parts from a lot, which can be opened from the lots info page.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/5410681/211223325-dc41897c-5e94-492f-a41b-7e8a2b5dc4c3.png">

**Comment by elperepat** [comment]
Could the modal form and the fields be a little bit narrower, to fit on a small screen? As it is now, I have to scroll sideways on my cellphone to view the form correctly. The rest of the website is liquid, as expected. This form isn't.

![Screenshot from 2023-01-08 19-14-15](https://user-images.githubusercontent.com/3879635/211225923-b4e5e04b-fde6-41fd-bad2-ee9ea0b233e8.png)

Thanks!

**Comment by jbtronics** [comment]
The modal should now properly fit the screen.
