### ISSUE TITLE
Create categories, storage locations etc. at part creation

### ISSUE THREAD

**Issue by suuppl** [Part-DB/Part-DB-symfony#203]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just quality of life.

**Describe the solution you'd like**
I would like to create categories, storage locations, packages etc. at part creation.
My ideal solution:
Start typing in the category search field. If the category exists, i can just use it. 
If not, part-db should create it. For subcategories, use slashes.

Example:
I am creating a part "BC817-25", there is a category "Transistors" and a subcategory "Transistors/BJT" but no "Transistor/BJT/NPN".
So I type "Transistor/BJT/NPN" in the category search field. As this category doesn't exist yet, show a button "Create new category" instead of "No results matched "Transistor/BJT/NPN"".

**Describe alternatives you've considered**
Create all categories (storage locations, ...) before filling in parts or go back and forth between categories and parts, but this slows down the part creation considerably

**Additional context**
Thank you for your work!

**Comment by virtadpt** [comment]
It would be handy.

**Comment by jbtronics** [comment]
In the newest version this is now possible. You can type in the new name in the entity select field, and click "Add".
Using "->" you can create nested structures.

![image](https://user-images.githubusercontent.com/5410681/215614377-84e80264-b780-434e-8268-81948b3e9dc8.png)

**Comment by suuppl** [comment]
That's awesome, thank you!
