### ISSUE TITLE
Dropdown menus are hidden behind other elements

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#209]
**Describe the bug**
Print dropdown menu (and others) disappear behind some other element

**To Reproduce**
1. Go to a part and click on the print icon

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1753222/215842025-819caa94-5deb-4df4-b285-d9a6808cb699.png)

![image](https://user-images.githubusercontent.com/1753222/215842279-ac47bbf2-1de3-47db-a522-4824509cfed1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox (latest), Vivaldi (latest)

**Comment by jbtronics** [comment]
Should be fixed now.
