### ISSUE TITLE
Bauteil kopieren erzeugt falschen Logeintrag

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#25]
Ich habe auf Bauteil kopieren geklickt:
![image](https://user-images.githubusercontent.com/59479028/76164638-cb0b1300-6150-11ea-8772-39dfc36e7054.png)

Nach dem kopieren, erscheint im zu kopierenden Teil im Log, dass der Preis geändert wurde.
![image](https://user-images.githubusercontent.com/59479028/76164651-db22f280-6150-11ea-898c-0c6cdf13b9c8.png)

Ich hätte auch erwartet, dass Einkaufsinformationen mit auf das neue Teil übertragen werden, die sind dort aber nicht hinterlegt. Ich weiß nicht ob das beabsichtigt ist.

**Comment by jbtronics** [comment]
Ist behoben. Danke für den Hinweis.
