### ISSUE TITLE
Letzte Aktivitäten nicht aussagekräftig

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#26]
Ich habe die Beschreibung des Lagerorts geändert:
![image](https://user-images.githubusercontent.com/59479028/76203858-a0c06080-61f7-11ea-9126-ef6baaaa5484.png)

Im Log auf der Startseite steht dann:
![image](https://user-images.githubusercontent.com/59479028/76203829-91d9ae00-61f7-11ea-8b23-e93013f8836e.png)

1. Ich denke, da sollte dann auch ersichtlich sein, welches Bauteil ich geändert habe.
2. Als geänderte Eigenschaft ist description nicht eindeutig, es könnte genauso gut die Bauteil-Beschreibung gemeint sein und nicht die vom Lagerort.
3. Ich habe nicht den Preis geändert, steht trotzdem im Log

**Comment by coeka** [comment]
Das passiert nicht nur beim Preis, dass der als geänderte Eigenschaft im Log steht, obwohl nicht geändert. Hier habe ich zum Beispiel nur die Beschreibung geändert, im Log steht aber das ich auch das Expiration Date geändert habe

![image](https://user-images.githubusercontent.com/59479028/76700068-dbbd0b00-66b3-11ea-85b4-6239a08c9664.png)

**Comment by jbtronics** [comment]
Sollte behoben sein.
