### ISSUE TITLE
Expiration date wrong

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#30]
I enter this date:
![image](https://user-images.githubusercontent.com/59479028/76699879-e9719100-66b1-11ea-8df1-2850bb3859f0.png)

I click on save changes:
![image](https://user-images.githubusercontent.com/59479028/76699889-00b07e80-66b2-11ea-8f9d-e56abff7c47f.png)

The correct date is saved:
![image](https://user-images.githubusercontent.com/59479028/76699898-1c1b8980-66b2-11ea-964a-74d0a7d51a21.png)

But when i click on edit to change for example the amount, there is the wrong date filled in and the wrong date will be saved. The difference is always 1 hour.

Despite this bug, i think the important thing is the date and the time should be optional.

**Comment by jbtronics** [comment]
Is now fixed.
I removed the time select completly, I don't think this is important for expiration dates at all.
Also now the HTML5 date picker is used, which should improve user experience when choosing a date.
