### ISSUE TITLE
Empty page when creating new element (user/category etc)

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#35]
**Describe the bug**
When I create a new element (like a user or a category) and pressed save, I just get a empty page. The problem also occurs in the demo instance

**To Reproduce**
1. Go to Tools --> Edit --> Category
2. Enter a Name
3. Press Save

**Expected behavior**
Either redirect to element list or show the saved element

**Server Side**
- Part-DB Version: e654c46e11d5eab780c12f069a4d2d2050ae2b65
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 2.11.1811.52 (Stable channel) (32-Bit)

**Additional context**
I am not sure whether you already like such error reports for the dev version?

**Comment by jbtronics** [comment]
Fixed the issue. It was cause by a left over dump() call. I have added a plugin to Continous Integration Testing, so this will be hopefully be found automatically in the future.
