### ISSUE TITLE
Error while opening part when exchange rate is empty

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#37]
**Describe the bug**
If the exchange rate for a currency is empty I get the following error when opening a part
`[2020-04-06 14:40:54] request.CRITICAL: Uncaught PHP Exception TypeError: "bcadd() expects parameter 2 to be string, null given" at /var/www/partdb/src/Services/PricedetailHelper.php line 177 {"exception":"[object] (TypeError(code: 0): bcadd() expects parameter 2 to be string, null given at /var/www/partdb/src/Services/PricedetailHelper.php:177)"} []`

**To Reproduce**
1. Create a currency with a empty ("") exchange rate
2. Assign this exchange rate to a supplier
3. Add this supplier to a part, enter some prices and save the part
4. Try to open the part again

**Expected behavior**
Default value for the exchange rate should be 1. An empty value shouldn't be allowed.

**Server Side**
- Part-DB Version: e654c46e11d5eab780c12f069a4d2d2050ae2b65
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 2.11.1811.52 (Stable channel) (32-Bit)

**Additional context**
I am not sure whether you already like such error reports for the dev version?

**Comment by jbtronics** [comment]
Indeed, I have intended that exchange rates can be null (meaning we have no info about it yet). If an price info use a currency without an exchange rate, it will just be excluded from calculation (at least if you want the result in another currency).

For the moment I fixed it that it works again like I originally intended. Maybe I will change it in the future.

But I don't think 1.0 would be a good default value for exchange rate, as this is (almost) always wrong and will lead to wrong results. And I think no results, are better than wrong results (e.g. for average price).
