### ISSUE TITLE
Error 500 when displaying statistics

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#38]
**Describe the bug**
Statistics show error (500) when no items with stock are available. 
`[2020-04-06 14:49:21] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Repository\PartRepository::getPartsInstockSum() must be of the type string, null returned" at /var/www/partdb/src/Repository/PartRepository.php line 68 {"exception":"[object] (TypeError(code: 0): Return value of App\\Repository\\PartRepository::getPartsInstockSum() must be of the type string, null returned at /var/www/partdb/src/Repository/PartRepository.php:68)"} []`

**To Reproduce**
1. Having a new installation with only one part without any stock
2. Click Tools --> Show --> Statistics

**Expected behavior**
Maybe the function getPartsInstockSum should return 0 instead of null?

**Server Side**
- Part-DB Version: e654c46e11d5eab780c12f069a4d2d2050ae2b65
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 2.11.1811.52 (Stable channel) (32-Bit)

**Additional context**
I am not sure whether you already like such error reports for the dev version?

**Comment by jbtronics** [comment]
Should be fixed.
