### ISSUE TITLE
Error 500 when adding a new part and footprint filter is applied

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#40]
**Describe the bug**
I selected a footprint (e.g. https://part-db.herokuapp.com/en/footprint/65/parts) and pressed the "Create new Part" button --> Error 500. I see the following error in the logfile:
`[2020-04-06 22:47:07] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The identifier id is missing for a query of App\Entity\Parts\Footprint" at /var/www/partdb/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 309 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The identifier id is missing for a query of App\\Entity\\Parts\\Footprint at /var/www/partdb/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:309)"} []`

**To Reproduce**
Please see description above

**Expected behavior**
Create a new part with the selected footprint pre-selected.

**Server Side**
- Part-DB Version: 9a30ea51590859f559955ce59c75e1c4df14278e
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 2.11.1811.52 (Stable channel) (32-Bit)

**Comment by jbtronics** [comment]
Fixed.
