### ISSUE TITLE
Error 500 when undelete the stock first

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#41]
I deleted a Part with stock. There a 3 entries in the log.
When i try to undelete the stock first, with this button:
![image](https://user-images.githubusercontent.com/59479028/78702685-45be7e00-7909-11ea-8a1d-5c0da1b7658d.png)
I get this message:
![image](https://user-images.githubusercontent.com/59479028/78702746-5d960200-7909-11ea-8f44-9e5a71ea20a0.png)

When i first undelete the Part itself and then undelete the Stock, everything is fine. I think there should be an errormessage, which tells me what i did wrong.

**Comment by jbtronics** [comment]
This is most likely related too an issue fixed a while ago. If this error still persists, open a new issue please.
