### ISSUE TITLE
"Clone Part" does not copy properties to new part 

### ISSUE THREAD

**Issue by MilanDeruelle** [Part-DB/Part-DB-symfony#46]
**Describe the bug**
I created a part with 2 properties. When using the clone button, the edit-view contains the original parts parameters correctly, for which I update the values to match the new part. When clicking on save the new, cloned part is correctly created (name, stock) but is missing the properties. The new part has no properties, instead the original parts properties are edited 

**Additional context**
Let me know if you have problems reproducing this and I will edit this to provide more information.

**Comment by jbtronics** [comment]
Fixed.
