### ISSUE TITLE
Error 500 when deleting image from part

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#50]
**Describe the bug**
I deleted a image from a part (the image was the preview image as well) and got the following error:
`[2020-05-09 18:16:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'DELETE FROM `attachments` WHERE id = ?' with params [25]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partdb`.`parts`, CONSTRAINT `FK_6940A7FE6DEDCEC2` FOREIGN KEY (`id_preview_attachement`) REFERENCES `attachments` (`id`))" at /var/www/partdb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 49 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'DELETE FROM `attachments` WHERE id = ?' with params [25]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partdb`.`parts`, CONSTRAINT `FK_6940A7FE6DEDCEC2` FOREIGN KEY (`id_preview_attachement`) REFERENCES `attachments` (`id`)) at /var/www/partdb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:49, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partdb`.`parts`, CONSTRAINT `FK_6940A7FE6DEDCEC2` FOREIGN KEY (`id_preview_attachement`) REFERENCES `attachments` (`id`)) at /var/www/partdb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partdb`.`parts`, CONSTRAINT `FK_6940A7FE6DEDCEC2` FOREIGN KEY (`id_preview_attachement`) REFERENCES `attachments` (`id`)) at /var/www/partdb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []`

**To Reproduce**
1. Open part https://part-db.herokuapp.com/en/part/964/edit
2. Click Attachments
3. Click Delete
4. Click Save Changes
5. See error

**Expected behavior**
No Error message and deleted image

**Server Side**
- Part-DB Version: aafe01811ed15ad5b748aec31a4b0c8b4a0b6912
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.0.1874.38 (Stable channel) (32-Bit)

**Comment by jbtronics** [comment]
Fixed.
