### ISSUE TITLE
.htaccess gz encoding error

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#53]
**Describe the bug**
When using the latest master version the css and js files are not loading correctly. I just see binary garbage in the brower. 

I found out that I had to change the lines 
```
<Files *.js.gz>
    AddType "text/javascript" .gz
    AddEncoding gz .gz
</Files>
<Files *.css.gz>
    AddType "text/css" .gz
    AddEncoding gz .gz
</Files>
<Files *.svg.gz>
    AddType "image/svg+xml" .gz
    AddEncoding gz .gz
</Files>
<Files *.html.gz>
    AddType "text/html" .gz
    AddEncoding gz .gz
</Files>
```

to 

```
<Files *.js.gz>
    AddType "text/javascript" .gz
    AddEncoding gzip .gz
</Files>
<Files *.css.gz>
    AddType "text/css" .gz
    AddEncoding gzip .gz
</Files>
<Files *.svg.gz>
    AddType "image/svg+xml" .gz
    AddEncoding gzip .gz
</Files>
<Files *.html.gz>
    AddType "text/html" .gz
    AddEncoding gzip .gz
</Files>
```

I am not sure if this is OS specific or a general typo in the .htaccess file?

**Server Side**
- Part-DB Version: d4e16a8b70fba6b2b2b1e54c896e515baa9d2faf
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10
- OS Version: Debian Buster

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.0.1874.38 (Stable channel) (32-Bit)

**Comment by jbtronics** [comment]
Thank you very much. My browser supports brotli encoding (which has higher priority), so I did not noticed it...

Should be fixed now.
