### ISSUE TITLE
Dates on labels seem to be in UTC

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#54]
**Describe the bug**
When printing a label e.g. for a location and adding the ​[[CREATION_DATE]]​ placeholder, the shown time seems to be in UTC independent of the date.timezone setting in the php.ini.
The creation date in the location "Info" tab in the location edit menu seems to be right (https://part-db.herokuapp.com/en/store_location/385/edit#info)
Not sure if this behavior is expected or wanted?

**Expected behavior**
Maybe show the same time as on other info screens?

**Screenshots**
![image](https://user-images.githubusercontent.com/1753222/81588917-4db28780-93b9-11ea-9e31-3eebfdb7abd7.png)

![image](https://user-images.githubusercontent.com/1753222/81588686-2bb90500-93b9-11ea-8d30-f7bd2674841d.png)

**Server Side**
Current version at https://part-db.herokuapp.com/en/

**Comment by jbtronics** [comment]
Fixed.
