### ISSUE TITLE
Direct jump from editing storage location to the storage location

### ISSUE THREAD

**Issue by coeka** [Part-DB/Part-DB-symfony#55]
In Part-DB 0.6 you can directly jump to the storage location, when you are editing the storage location. It would be nice to have the same feature in Part-DB-Symphony.

Part-DB 0.6:
![image](https://user-images.githubusercontent.com/59479028/81594159-c36e2180-93c0-11ea-9a2d-a4180a98ed9a.png)

**Comment by jbtronics** [comment]
Added this feature.
