### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#56]
**Describe the bug**
The following strings are not translated (they exist in crowdin but it seems not to work:
- https://part-db.herokuapp.com/en/user/settings#configuration : user.theme.label
- https://part-db.herokuapp.com/en/user/settings#configuration : user_settings.theme.placeholder
- https://part-db.herokuapp.com/en/label_profile/new :  label_profile.showInDropdown
- https://part-db.herokuapp.com/en/group/new : group.edit.enforce_2fa
- https://part-db.herokuapp.com/en/group/new : entity.edit.enforce_2fa.help

- https://part-db.herokuapp.com/en/manufacturer/new#common : Parent Element shows "Nothing selected in every language"

**Server Side**
Demo Server https://part-db.herokuapp.com/en

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Vivaldi
- Version 3.0.1874.38 (Stable channel) (32-Bit)

**Comment by jbtronics** [comment]
fixed.
