### ISSUE TITLE
When duplicating a part, the attachments aren't duplicated

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#71]
**Describe the bug**
If I duplicate a part with an attachment, the attachment itself is not duplicated as well. That means, if I delete the attachment from the new (duplicated part) the attachment is also removed from the orignial part.

**Expected behavior**
I would have expected that the attachments are copied on the hard disc.

**Server Side**
- Part-DB Version: 59d1349ce8db82573005851f8d5021564f697c1d
- PHP Version: PHP 7.3.16
- Database Server 10.3.22-MariaDB-0+deb10u1 Debian 10

**Desktop:**
 - OS: Windows 10
 - Browser Firefox
 - Version 77.0.1 (64-Bit)

**Comment by jbtronics** [comment]
Fixed.
