### ISSUE TITLE
Unable to change stock quantity if store location is marked as "Limit to existing parts"

### ISSUE THREAD

**Issue by tbnobody** [Part-DB/Part-DB-symfony#72]
**Describe the bug**
If a Store location is marked as "Limit to existing parts" it's not possible to change the stock amount of a part which is assinged to this location.

**To Reproduce**
1. https://part-db.herokuapp.com/en/part/961/edit
2. Change Stock Amount from 50 to something else
3. Apply changes

**Comment by jbtronics** [comment]
Fixed.
