### ISSUE TITLE
Part categories

### ISSUE THREAD

**Issue by Murmele** [Part-DB/Part-DB-symfony#77]
I think this feature is not that important, because alternatives and the partnumber it self can be found also by using the distributor search, then in the database the part can be selected.
The idea is to combine this database with an EDA tool (for example https://kicad-pcb.org/). And so automatically assigning automatically properties and footprint (https://forum.kicad.info/t/automatic-assignement-of-footprint-and-3d-model/24497).

**Is your feature request related to a problem? Please describe.**
Distributors are using categories to sort their parts. So each category has it's own list of parameter which can be selected.
For example ThinkFilm Resistors:

[Mouser:  All Products  -> Passive Components -> Resistors SMD Resistors / Chip Resistors -> Thick Film Resistors ](https://www.mouser.de/Passive-Components/Resistors/SMD-Resistors-Chip-Resistors/Thick-Film-Resistors/_/N-7h7yz?Ns=Pricing|0)

The Thick Film Resistors category has the properties :Manufacturer, Series, Resistance, Power Rating, Tolerance, Temperature Coefficient, Case Code ...
The upper category (Resistors SMD Resistors / Chip Resistors) has only the properties: Manufacturer, Resistance, Tolerance, Power Rating, Case Code

This is usefull for finding alternatives.

**Describe the solution you'd like**
It would be nice it is possible to create categories, subcategories and so on (which have specific properties which can be used to find a part).
Each part can then be assigned to a categorie (get assigned also the upper categorie). So searching for a specific part becomes quite easy

**Comment by jbtronics** [comment]
You can define parameters for a part on a part level now (which is a bit more flexible, as maybe not all parts in a category have the same properties, also the inheritance logic would be pretty complicated).
You can add filters, to only show parts of a category which fullfills given conditions (based on value or text content), so the wished feauture should be possible now.
