### ISSUE TITLE
Migration error with mariadb

### ISSUE THREAD

**Issue by chrisnoisel** [Part-DB/Part-DB-symfony#8]
I ran into an issue installing partdb with mariadb, I've not the error message any more but if I remember well the database migration tool uses DEFAULT CURRENT_TIMESTAMP on a DATETIME column but it is only supported since  [mariaDB 10.0.1](https://mariadb.com/kb/en/datetime/). Some Linux distribution may not package a recent enough version in their default repositories.

It is probably a good idea to add that information in the readme since it's not obvious when it fails :)

**Comment by jbtronics** [comment]
I have added info about minimum versions to README.
I don't think it is worth to support almost 7 years old version of MariaDB, where every recent distro includes much newer versions, so I will not fix it in actual code (also this would break existing migrated DBs).
