### ISSUE TITLE
Cannot add Images/attachments to Store locations

### ISSUE THREAD

**Issue by the78mole** [Part-DB/Part-DB-symfony#81]
**Describe the bug**
When trying to add images to store locations, an internal server error occurs

**To Reproduce**
1. Edit store location
2. Add Image by browse
3. Click on Save

**Expected behavior**
Like with parts or footprints, locations an image is attached to the location

**Screenshots**
![image](https://user-images.githubusercontent.com/7723396/94365253-85ec0580-00cf-11eb-8b4f-399e93ca17b7.png)

**Server Side**
- Part-DB Version: git 44ec940
- PHP Version: PHP 7.3 (Debian 10.0 Buster)
- Database Server MariaDB 10.3.23 (Debian 10.0 Buster)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  85.0.4183.102

**Comment by jbtronics** [comment]
Fixed.
