### ISSUE TITLE
 %PARTNR% vs %PARTNUMBER%

### ISSUE THREAD

**Issue by paultech** [Part-DB/Part-DB-symfony#84]
Tooltip mentions ` %PARTNR% will be replaced with the order number.`  however the code uses `%PARTNUMBER%` to do the field replacement.

https://github.com/Part-DB/Part-DB-symfony/blob/28e7e401d412e425f0588f6c6c0baecd7db11c21/translations/messages.en.xlf#L7219

https://github.com/Part-DB/Part-DB-symfony/blob/483d6854bf47515005b3b5728256c45b267a63b9/src/Entity/Base/AbstractCompany.php#L161

Let me know if a PR would be easier.

**Comment by jbtronics** [comment]
Should be fixed now.
