### ISSUE TITLE
backup/restore documentation

### ISSUE THREAD

**Issue by 927589452** [Part-DB/Part-DB-symfony#86]
**Is your feature request related to a problem? Please describe.**
The old part-db had documentation on what was needed to backup an what was needed to restore

**Describe the solution you'd like**
List of files / directories to backup 

**Describe alternatives you've considered**
A php script to create an backup archive like `php bin/console backup:{create, restore}`

**Comment by jbtronics** [comment]
(Basic) Backup and Restore instructions can now be found here: https://github.com/Part-DB/Part-DB-symfony/wiki/Backup-&-Restore-Data.

Also there now is a command `php bin/console partdb:backup` which creates a ZIP file with all back-uped data (e.g. `php bin/console/partdb:backup --full /root/backup.zip`

**Comment by virtadpt** [comment]
Woot!  Thank you!
