### ISSUE TITLE
Server gets stuck on 500 Internal Server Error if unsupported image attached to part

### ISSUE THREAD

**Issue by stenstad** [Part-DB/Part-DB-symfony#89]
If you upload any image not supported by gd.so, the server will throw an execption in /var/www/html/vendor/imagine/imagine/src/Gd/Imagine.php at line 95, since createImageFromString($data) above it only creates a valid resource if GD supports the image format.

The GD bundled with the docker image (jbtronics/part-db1:latest) does not support a lot of formats. PNG works, JPEG or WEBP does not.

It should probably fail more gracefully, as you need to delete the file on disk to get PartDB running again.

**To Reproduce**
1. Add an attachment to any part.
2. Upload a jpeg.
3. Wonder why PHP is not able to access the file on disk.

**Comment by Chris-42** [comment]
seema again to be a problem

**Comment by jbtronics** [comment]
Part-DB should dont throw an exception which makes it impossible to continue now. Instead, the original file is served, if no thumbnail can be generated.
