### ISSUE TITLE
1D Barcode subtitle is printed behind Barcode

### ISSUE THREAD

**Issue by Marioheld** [Part-DB/Part-DB-symfony#91]
When trying to print 1D Barcodes (Code 128, Code 39 or Code 93) on labels (Storage location, Part lot, or Part) the subtilte of the barcode is printed behind the barcode itself. 
Are there any ways in the label generator to modify the barcode layout? 

**Screenshot**
![barcode](https://user-images.githubusercontent.com/4212288/103888918-da971780-50e5-11eb-8e88-f1d6f88ce04a.PNG)

**Tested Versions**
- Latest checkout from master branch on Debian 10
- Heroku Instance EN and DE

**Comment by Mellerin** [comment]
Hello,
I am currently trying out Part-DB with the same Heroku(en) instance, and I could see this while testing this feature (with Firefox latest version, didn't try another browser).The Part-DB-symfony/templates/LabelSystem/labels/label_style.css.twig file contains the CSS for rendering this label.
When creating a label, you can change the style in the "Advanced" tab, I copy-pasted the style defined in the said file and modified it like this:

```
.C39-container {
    display: inline-block;
    align-content: center;
    text-align: left;
    position: fixed;
    bottom: 50px;
}

.C39-text {
    display: block;
    margin-top: 6px;
    font-size: 6pt;
}
```
I don't know much about CSS or styles, but by playing with the values I found a rendering that works with Code 39/93/128.
![Capture d’écran de 2021-03-14 13-07-17](https://user-images.githubusercontent.com/36613276/111068078-7f0f4e80-84c7-11eb-8479-0f3405034a79.png)

@ dev and all contributor : thanks for this promising app :)

**Comment by jbtronics** [comment]
This was fixed some time ago.
