### ISSUE TITLE
Auto-generated Manufacturer URL should use part number instead of name

### ISSUE THREAD

**Issue by smrqdt** [Part-DB/Part-DB-symfony#93]
The auto-generated manufacturer URL currently uses the _part name_ to replace `%PARTNUMBER%` in the product URL, it should use the _manufacturer part number_.

I think this line is the relevant one:
https://github.com/Part-DB/Part-DB-symfony/blob/3328dd968d27587c747718bef4569227416511ed/src/Entity/Parts/PartTraits/ManufacturerTrait.php#L101

**Comment by jbtronics** [comment]
Is implemented now.
