### ISSUE TITLE
Help me to install simply on UBUNTU 20.04.

### ISSUE THREAD

**Issue by mnemorex** [Part-DB/Part-DB-symfony#95]
Hello,

already, well done for this application, but, I have been trying for several weeks to install the files and I can not achieve anything.

I started with a virgin installation of UBUNTU 20.04 (and reinstalled several times, without any effect) and i read a few wikis, or doc, but i got stuck at various times.

My question, is there anyone who could help me install the program just from 0 ?.

I'm not a specialist, just Hobby-man.

Thank you.

**Comment by TheEris** [comment]
I would love a step-by-step guide to setup this on ubuntu

**Comment by Pyromane** [comment]
Install Docker
```
apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
curl -fsSL http://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] http://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
```

Download the Docker Image and start it
```
docker pull jbtronics/part-db1
docker run --name Part-DB --restart=unless-stopped -d -p 80:80 jbtronics/part-db1
docker exec --user=www-data Part-DB bin/console doctrine:migrations:migrate
```
The Admin PW will now be displayed.
