### ISSUE TITLE
Mixed content with HTTPS

### ISSUE THREAD

**Issue by TheEris** [Part-DB/Part-DB-symfony#96]
**Describe the bug**
Mixed content when using reverse proxy and HTTPS. Cannot use the menu on right - no items in it

when accessing it via IP in local networks, everything works ok.

**To Reproduce**
setup a standalone docker image and setup reverse proxy that forces HTTPS (I'm using NginxProxyManager).

**Screenshots**
Missing "Tools, Edit, Show...."
![image](https://user-images.githubusercontent.com/11465188/112502959-d1375600-8d8a-11eb-8f68-fd18750350fc.png)

Errors in Chrome
![image](https://user-images.githubusercontent.com/11465188/112503705-718d7a80-8d8b-11eb-8f6e-f9ca744f770c.png)
![image](https://user-images.githubusercontent.com/11465188/112503777-7f430000-8d8b-11eb-90d9-534f2f68cb79.png)

**Server Side**
jbtronics/part-db1:master
running on Unraid 6.9.1

**Comment by jbtronics** [comment]
Thats most likely caused by a not set TRUSTED_PROXIES env variable. See issue #145 and the new section about reverse proxies in README.md
