### ISSUE TITLE
"Devices" - not implemented yet?

### ISSUE THREAD

**Issue by mueschel** [Part-DB/Part-DB-symfony#97]
Are "Devices" not yet implemented in the current version?
It seems like nothing happens when selecting a device from the list. This is not mentioned in the Readme and the features not yet implemented.

**Comment by jbtronics** [comment]
Yes the device feature is not implemented yes, and will most likely changed a bit from the original Part-DB version, when it will be implemented, to become more useful.

**Comment by jbtronics** [comment]
The old devices are now available (in a very basic form) as projects in the most recent Part-DB version.
